# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# Baseurl = name of github repository linked to libertarianinstitute account
#
#
title: Libertariani.cz - Policie pomáhající a chránící
email: michal.kurz@libertariani.cz
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/policie-pomahajici-a-chranici" # the subpath of your site, e.g. /blog
url: "http://libertarianinstitute.github.io" # the base hostname & protocol for your site
github_username:  libertarianinstitute

# Build settings
markdown: kramdown
